-- Migration: populate emoji values for existing badges
ALTER TABLE badges ADD COLUMN IF NOT EXISTS emoji VARCHAR;

UPDATE badges SET emoji = '🐺' WHERE name = 'Lone Wolf';
UPDATE badges SET emoji = '🦅' WHERE name = 'Alpha Predator';
UPDATE badges SET emoji = '👑' WHERE name = 'Wolf Pack Leader';
UPDATE badges SET emoji = '⚡' WHERE name = 'Apex Lone Wolf';
UPDATE badges SET emoji = '🤝' WHERE name = 'Dynamic Duo';
UPDATE badges SET emoji = '💎' WHERE name = 'Perfect Partnership';
UPDATE badges SET emoji = '🎲' WHERE name = 'High Roller';
UPDATE badges SET emoji = '💪' WHERE name = 'Pressure Player';
UPDATE badges SET emoji = '🃏' WHERE name = 'The Gambler';
UPDATE badges SET emoji = '☭' WHERE name = 'Karl Marx''s Favorite';
UPDATE badges SET emoji = '🦄' WHERE name = 'Unicorn';
UPDATE badges SET emoji = '🏆' WHERE name = 'Perfect Game';
UPDATE badges SET emoji = '🔥' WHERE name = 'Lazarus';
UPDATE badges SET emoji = '🥉' WHERE name = 'Bronze Earner';
UPDATE badges SET emoji = '🥈' WHERE name = 'Silver Earner';
UPDATE badges SET emoji = '🥇' WHERE name = 'Gold Earner';
UPDATE badges SET emoji = '💰' WHERE name = 'Platinum Earner';
UPDATE badges SET emoji = '💎' WHERE name = 'Diamond Earner';
UPDATE badges SET emoji = '🌱' WHERE name = 'Rookie';
UPDATE badges SET emoji = '🍽️' WHERE name = 'Banquet Eligible';
UPDATE badges SET emoji = '⛳' WHERE name = 'Journeyman';
UPDATE badges SET emoji = '🎖️' WHERE name = 'Veteran';
UPDATE badges SET emoji = '🌟' WHERE name = 'Legend';
UPDATE badges SET emoji = '♾️' WHERE name = 'Immortal';
UPDATE badges SET emoji = '⚔️' WHERE name = 'Scrapper';
UPDATE badges SET emoji = '🥊' WHERE name = 'Competitor';
UPDATE badges SET emoji = '🏅' WHERE name = 'Champion';
UPDATE badges SET emoji = '👊' WHERE name = 'Dominator';
UPDATE badges SET emoji = '🛡️' WHERE name = 'Untouchable';
UPDATE badges SET emoji = '🔩' WHERE name = 'Iron Will';
UPDATE badges SET emoji = '💥' WHERE name = 'Consistent Crusher';
UPDATE badges SET emoji = '😤' WHERE name = 'Dominance';
UPDATE badges SET emoji = '🌩️' WHERE name = 'Godlike';
UPDATE badges SET emoji = '⚔️' WHERE name = 'War';
UPDATE badges SET emoji = '💀' WHERE name = 'Famine';
UPDATE badges SET emoji = '🦠' WHERE name = 'Pestilence';
UPDATE badges SET emoji = '💀' WHERE name = 'Death';
UPDATE badges SET emoji = '🌋' WHERE name = 'Apocalypse Master';
UPDATE badges SET emoji = '🎆' WHERE name = 'New Year Dominator';
