"""
Schema package — domain-split Pydantic models.

All schemas are re-exported here so existing code using
``from .. import schemas`` + ``schemas.ClassName`` continues to work.
"""

from .betting import (
    GameSetupRequest,
    OddsCalculationRequest,
    ShotAnalysisRequest,
)
from .courses import (
    CourseComparison,
    CourseCreate,
    CourseImportRequest,
    CourseList,
    CourseResponse,
    CourseStats,
    CourseUpdate,
    HoleInfo,
)
from .games import (
    ActionRequest,
    ActionResponse,
    CompleteHoleRequest,
    GamePlayerResultCreate,
    GamePlayerResultResponse,
    GameRecordCreate,
    GameRecordResponse,
    GameRecordUpdate,
    HoleTeams,
    JoinGameRequest,
    ManualPointsOverride,
    RotationSelectionRequest,
    Rule,
)
from .players import (
    LeaderboardEntry,
    PlayerAchievementResponse,
    PlayerPerformanceAnalytics,
    PlayerProfileBase,
    PlayerProfileCreate,
    PlayerProfileResponse,
    PlayerProfileUpdate,
    PlayerProfileWithStats,
    PlayerStatisticsResponse,
)
from .signups import (
    DailyMessageCreate,
    DailyMessageResponse,
    DailyMessageUpdate,
    DailySignupCreate,
    DailySignupResponse,
    DailySignupSummary,
    DailySignupUpdate,
    DailySignupWithMessages,
    EmailPreferencesCreate,
    EmailPreferencesResponse,
    EmailPreferencesUpdate,
    GameBannerCreate,
    GameBannerResponse,
    GameBannerUpdate,
    MatchPlayerResponse,
    MatchResponseRequest,
    MatchSuggestionResponse,
    PlayerAvailabilityCreate,
    PlayerAvailabilityResponse,
    PlayerAvailabilityUpdate,
    PlayerAvailabilityWithMatchesResponse,
    PlayerWithAvailability,
    WeeklySignupView,
    WeeklySignupWithMessagesView,
)

__all__ = [
    # courses
    "CourseComparison",
    "CourseCreate",
    "CourseImportRequest",
    "CourseList",
    "CourseResponse",
    "CourseStats",
    "CourseUpdate",
    "HoleInfo",
    # players
    "LeaderboardEntry",
    "PlayerAchievementResponse",
    "PlayerPerformanceAnalytics",
    "PlayerProfileBase",
    "PlayerProfileCreate",
    "PlayerProfileResponse",
    "PlayerProfileUpdate",
    "PlayerProfileWithStats",
    "PlayerStatisticsResponse",
    # games
    "ActionRequest",
    "ActionResponse",
    "CompleteHoleRequest",
    "GamePlayerResultCreate",
    "GamePlayerResultResponse",
    "GameRecordCreate",
    "GameRecordResponse",
    "GameRecordUpdate",
    "HoleTeams",
    "JoinGameRequest",
    "ManualPointsOverride",
    "RotationSelectionRequest",
    "Rule",
    # signups
    "DailyMessageCreate",
    "DailyMessageResponse",
    "DailyMessageUpdate",
    "DailySignupCreate",
    "DailySignupResponse",
    "DailySignupSummary",
    "DailySignupUpdate",
    "DailySignupWithMessages",
    "EmailPreferencesCreate",
    "EmailPreferencesResponse",
    "EmailPreferencesUpdate",
    "GameBannerCreate",
    "GameBannerResponse",
    "GameBannerUpdate",
    "MatchPlayerResponse",
    "MatchResponseRequest",
    "MatchSuggestionResponse",
    "PlayerAvailabilityCreate",
    "PlayerAvailabilityResponse",
    "PlayerAvailabilityUpdate",
    "PlayerAvailabilityWithMatchesResponse",
    "PlayerWithAvailability",
    "WeeklySignupView",
    "WeeklySignupWithMessagesView",
    # betting
    "GameSetupRequest",
    "OddsCalculationRequest",
    "ShotAnalysisRequest",
]
